In [53]:
import pandas as pd
import numpy as np

In [54]:
months = ["jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"]
days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
non_leap_start_index = [1, 32, 60, 91, 121, 152, 182, 213, 244, 274, 305, 335]
non_leap_end_index = [31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334, 365]

leap_start_index = [1, 32, 61, 92, 122, 153, 183, 214, 245, 275, 306, 336]
leap_end_index = [31, 60, 91, 121, 152, 182, 213, 244, 274, 305, 335, 366]

In [55]:
data = pd.read_csv("../eda/NE_available.csv")
data.drop(["Unnamed: 0"], inplace=True, axis=1)
data.head()

latitude  longitude
0     22.00      93.00
1     22.25      92.50
2     22.25      92.75
3     22.25      93.00
4     22.50      92.50

In [56]:
year = 1901
end_year = 2018
for y in range(year, end_year+1):
    year_data = pd.read_csv(f"../NE_csv/{y}_rain.csv")
    is_leap = True if year_data.shape[1] == 369 else False

    if not is_leap:

        for i,start in enumerate(non_leap_start_index):
            start_col = year_data[f"{start}"]
            for j in range(start+1, non_leap_end_index[i]+1):
                start_col = start_col + year_data[f"{j}"]
            data[f"{y}_{months[i]}"] = start_col/(non_leap_end_index[i]-non_leap_end_index[i]+1)
    else:
        for i,start in enumerate(leap_start_index):
            start_col = year_data[f"{start}"]
            for j in range(start+1, leap_end_index[i]+1):
                start_col = start_col + year_data[f"{j}"]
            data[f"{y}_{months[i]}"] = start_col/(leap_end_index[i]-leap_end_index[i]+1)


/tmp/ipykernel_120/1634839523.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f"{y}_{months[i]}"] = start_col/(non_leap_end_index[i]-non_leap_end_index[i]+1)
/tmp/ipykernel_120/1634839523.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f"{y}_{months[i]}"] = start_col/(non_leap_end_index[i]-non_leap_end_index[i]+1)
/tmp/ipykernel_120/1634839523.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joini

In [57]:
data.head()

latitude  longitude  1901_jan  1901_feb  1901_mar  1901_apr  1901_may  \
0     22.00      93.00       0.0       0.0       0.0       0.0       0.0   
1     22.25      92.50       0.0       0.0       0.0       0.0       0.0   
2     22.25      92.75       0.0       0.0       0.0       0.0       0.0   
3     22.25      93.00       0.0       0.0       0.0       0.0       0.0   
4     22.50      92.50       0.0       0.0       0.0       0.0       0.0   

   1901_jun  1901_jul  1901_aug  ...   2018_mar   2018_apr    2018_may  \
0       0.0       0.0       0.0  ...   0.000000  20.072099  238.515110   
1       0.0       0.0       0.0  ...  11.249307  25.366446  336.818744   
2       0.0       0.0       0.0  ...   0.000000  24.207863  237.372700   
3       0.0       0.0       0.0  ...   0.000000  23.769324  237.500624   
4       0.0       0.0       0.0  ...  22.677995  30.755352  317.556866   

     2018_jun    2018_jul    2018_aug    2018_sep    2018_oct  2018_nov  \
0  313.169812  495.309844  887.072565  305.928007  299.334172  4.990988   
1  378.008197  791.334822  896.826624  300.347174  291.607087  4.537962   
2  365.741710  490.506965  861.164543  301.130734  292.486884  4.618853   
3  360.140828  491.027349  863.930082  301.659063  293.217801  4.658576   
4  422.348639  643.304656  849.949306  304.451175  286.215938  4.976906   

   2018_dec  
0  1.996395  
1  2.827179  
2  2.686064  
3  2.614564  
4  3.358955  

[5 rows x 1418 columns]

In [58]:
data_num = data.drop(["latitude", "longitude"], axis=1)
data_num.head()

1901_jan  1901_feb  1901_mar  1901_apr  1901_may  1901_jun  1901_jul  \
0       0.0       0.0       0.0       0.0       0.0       0.0       0.0   
1       0.0       0.0       0.0       0.0       0.0       0.0       0.0   
2       0.0       0.0       0.0       0.0       0.0       0.0       0.0   
3       0.0       0.0       0.0       0.0       0.0       0.0       0.0   
4       0.0       0.0       0.0       0.0       0.0       0.0       0.0   

   1901_aug  1901_sep  1901_oct  ...   2018_mar   2018_apr    2018_may  \
0       0.0       0.0       0.0  ...   0.000000  20.072099  238.515110   
1       0.0       0.0       0.0  ...  11.249307  25.366446  336.818744   
2       0.0       0.0       0.0  ...   0.000000  24.207863  237.372700   
3       0.0       0.0       0.0  ...   0.000000  23.769324  237.500624   
4       0.0       0.0       0.0  ...  22.677995  30.755352  317.556866   

     2018_jun    2018_jul    2018_aug    2018_sep    2018_oct  2018_nov  \
0  313.169812  495.309844  887.072565  305.928007  299.334172  4.990988   
1  378.008197  791.334822  896.826624  300.347174  291.607087  4.537962   
2  365.741710  490.506965  861.164543  301.130734  292.486884  4.618853   
3  360.140828  491.027349  863.930082  301.659063  293.217801  4.658576   
4  422.348639  643.304656  849.949306  304.451175  286.215938  4.976906   

   2018_dec  
0  1.996395  
1  2.827179  
2  2.686064  
3  2.614564  
4  3.358955  

[5 rows x 1416 columns]

In [59]:
X = data_num.to_numpy()

In [60]:
X

array([[  0.        ,   0.        ,   0.        , ..., 299.33417225,
          4.99098778,   1.99639511],
       [  0.        ,   0.        ,   0.        , ..., 291.60708666,
          4.53796244,   2.82717943],
       [  0.        ,   0.        ,   0.        , ..., 292.48688412,
          4.61885262,   2.68606442],
       ...,
       [  0.        ,   0.        ,   0.        , ...,  51.90000045,
         58.60000081,  14.59999979],
       [  0.        ,   0.        ,   0.        , ...,  51.90000069,
         58.59999986,  14.59999979],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ]])

In [61]:
np.save("1901_2018_monthly.npy", X)

Yearly average

In [62]:
i=0
X[:,12*i:(12*i + 12)]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [63]:
np.sum(X[:,12*i:(12*i + 12)], axis=1)/12

array([  0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        , 134.34166294,   0.        ,
         0.        ,   0.        , 134.34165597, 134.24321971,
       138.29077664, 195.00225599, 188.13090895, 183.46875977,
       190.4253903 ,   0.        , 134.25456478, 136.38372561,
       154.46163118, 192.78183562, 189.57762191, 186.91842847,
       187.03676366, 178.88641478,   0.        , 134.69053014,
       141.50296195, 175.28399407, 193.56871021, 192.2874055 ,
       189.49460146, 187.89361679, 190.60714807, 164.24564228,
       136.63843521, 156.13594431, 194.99580239, 192.80486287,
       192.14425542, 189.25957717, 192.29458489, 188.04699349,
       155.99191631, 130.09028124, 123.73077371, 123.56666573,
         0.        ,   0.        , 212.16944508, 195.6829475 ,
       189.57235926, 187.80842933, 196.17364768, 187.08252502,
       149.80397992, 129.58009205, 124.03094761, 123.56

In [64]:
data = pd.read_csv("../eda/NE_available.csv")
data.drop(["Unnamed: 0"], inplace=True, axis=1)
data.head()


year = 1901
end_year = 2018
i = 0
for y in range(year, end_year+1):
    data[f"{y}"] = np.sum(X[:,12*i:(12*i + 12)], axis=1)/12
    i = i + 1

data_num = data.drop(["latitude", "longitude"], axis=1)
data_num.head()

/tmp/ipykernel_120/3744880304.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f"{y}"] = np.sum(X[:,12*i:(12*i + 12)], axis=1)/12
/tmp/ipykernel_120/3744880304.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f"{y}"] = np.sum(X[:,12*i:(12*i + 12)], axis=1)/12
/tmp/ipykernel_120/3744880304.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To

1901  1902  1903  1904  1905  1906  1907  1908  1909  1910  ...  \
0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
1   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
2   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
3   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
4   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   

         2009        2010        2011        2012        2013        2014  \
0    0.000000    0.000000    0.000000    0.000000  224.739061  179.934938   
1  119.599994  129.756946  140.841661  180.491658  226.467797  179.785370   
2    0.000000    0.000000    0.000000    0.000000  219.337973  177.015148   
3    0.000000    0.000000    0.000000    0.000000  219.291902  176.985583   
4  119.600006  160.612051  140.841670  180.491672  238.820552  186.977357   

         2015        2016        2017        2018  
0   93.144936  159.703247  420.953914  213.865749  
1  168.634318  174.666363  409.684605  253.286562  
2   93.120128  159.556729  411.666454  215.028600  
3   93.119172  159.575142  412.662659  214.908384  
4  169.377455  176.475074  404.285266  240.849652  

[5 rows x 118 columns]

In [65]:
X2 = data_num.to_numpy()

np.save("1901_2018_yearly.npy", X2)
